config/routes.rb
Rails.application.routes.draw do
  
  get 'animalkinds/new'
  get 'favorites/new'
  get 'cities/new'
  get 'announcementcontacts/new'
  get 'announcementaddresses/new'
  get 'userinformations/new'
  get 'userinformation/new'
  get 'animals/new'
  get 'categories/new'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get 'search/announcements' => 'announcements#index'
  
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'search' => 'static_pages#search'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  post   'searchwithparams'   => 'static_pages#searchwithparams'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :announcements,   only: [:destroy, :index, :edit, :update, :new, :create, :show, :search]
  resources :categories,      only: [:index, :show]
  resources :animalkinds,      only: [:index, :show]
  resources :animals,         only: [:destroy, :edit, :new, :show, :index, :create, :update]
  resources :userinformations, only: [:destroy, :edit, :new, :show, :index, :create, :update]
  resources :announcementaddresses, only: [:destroy, :edit, :new, :show, :index, :create, :update]
  resources :announcementcontacts, only: [:destroy, :edit, :new, :show, :index, :create, :update]
  resources :favorites, only: [ :new, :index, :destroy, :create]
 

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    if logged_in?
      @announcement  = current_user.announcements.build
      @feed_items = current_user.feed.paginate(page: params[:page])
      @categories = Category.all
      @cities = City.all
      @animalkinds = Animalkind.all
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
  def search
    @announcement = Announcement.new
    #debugger
    #redirect_to announcements_path(:category_id => params[:category_id], :city_id => params[:city_id])
    
  end
  
  def searchwithparams
    @announcement = Announcement.new
    #debugger
    redirect_to announcements_path(id_params)
    #:category_id => params[:category_id], :city_id => params[:city_id]
  end
  
  def create_new_announcement
    if logged_in?
     @categories = Category.all
    end
  end
  
   def id_params
     params.require(:announcement).permit(:category_id, :city_id, :animalkind_id)
   end

  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<div class="MyBody">
  <% provide(:title, "About") %>
  <h1>About</h1>
  
  <p  class = "center">
      The platform is under development.
  </p>
</div>

app/views/static_pages/contact.html.erb
<div class="MyBody">
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p class = "center">
  All your questions about the application, you can write to the mail arttem_semenov _1997@mail.ru or via vk.com
  <a href="https://vk.com/artyomsemyonov97">contact page</a>.
</p>
</div>

app/views/static_pages/help.html.erb
<div class="MyBody">
<% provide(:title, "Help") %>
<h1>Help</h1>
<p class = "center">
  Write your problems to arttem_semenov_1997@mail.ru. 
</p>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="MyBody">
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
            <%= render 'shared/user_info' %>
        </section>
        <div class = "spaceforbuttom">
          <%= link_to "Создать новое объявление!", new_announcement_path, class: "btn btn-lg btn-primary" %>
        </div>
      </aside>
      <div class="col-md-8">
        <h3>Мои объявления</h3>
        <%= render 'shared/feed' %>
      </div>
    </div>
  </div>
<% else %>
  <div class="MyCenter jumbotron">
    <h1>Добро пожаловать в AnnouncementUnion!</h1>
    <br /><br />
    <%= link_to "Зарегиструйтесь сейчас!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  
  <div align="right">
<%#  <%= link_to image_tag("rails.png", alt: "Rails logo"),
              'http://rubyonrails.org/' %> 
  </div>
<% end %>
  <!--<provide(:title, "Home")%>-->

app/views/static_pages/search.html.erb
<div class="MyBody">
<% provide(:title, "Edit announcement") %>
<h1>Поиск</h1>

  <div class="MyContent">
  
  <% if logged_in? %>
      <%= form_for @announcement, :url => "searchwithparams" do |f|  %>
      <%= render 'shared/error_messages', object: f.object %>
       
        
        <div class="blocks-wrapper">
          <div class="text">
              <p> Категория: </p>
          </div>
          <div class="seldiv">
            <%= f.select :category_id, [['Розыск', 1],['Покупка', 2],['Продажа', 3]] %>
          </div>
  
        </div>
        
          <div class="blocks-wrapper">
          <div class="text">
              <p> Город: </p>
          </div>
          <div class="seldiv">
            <%= f.select :city_id, [['Москва', 1],['Санкт-Петербург', 2],['Нижний Новгород', 3],['Сочи', 4],['Казань', 5],['Ростов-на-Дону', 6]] %>
          </div>
          
        </div>
        
        <div class="blocks-wrapper">
          <div class="text">
              <p> Вид животного: </p>
          </div>
          <div class="seldiv">
            <%= f.select :animalkind_id, [['Кошки', 1],['Собаки', 2],['Попугаи', 3]] %>
          </div>
        </div>
      
          <div class="post">
            <%= f.submit 'Поиск', class: "btn btn-primary" %>
           <%#<%= link_to 'Date', announcements_path , params.merge(f: f) %>
          </div>
          
       <% end %>   
  <% end %>
  </div>
</div>