config/routes.rb
Rails.application.routes.draw do
  
  get 'animalkinds/new'
  get 'favorites/new'
  get 'cities/new'
  get 'announcementcontacts/new'
  get 'announcementaddresses/new'
  get 'userinformations/new'
  get 'userinformation/new'
  get 'animals/new'
  get 'categories/new'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get 'search/announcements' => 'announcements#index'
  
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'search' => 'static_pages#search'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  post   'searchwithparams'   => 'static_pages#searchwithparams'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :announcements,   only: [:destroy, :index, :edit, :update, :new, :create, :show, :search]
  resources :categories,      only: [:index, :show]
  resources :animalkinds,      only: [:index, :show]
  resources :animals,         only: [:destroy, :edit, :new, :show, :index, :create, :update]
  resources :userinformations, only: [:destroy, :edit, :new, :show, :index, :create, :update]
  resources :announcementaddresses, only: [:destroy, :edit, :new, :show, :index, :create, :update]
  resources :announcementcontacts, only: [:destroy, :edit, :new, :show, :index, :create, :update]
  resources :favorites, only: [ :new, :index, :destroy, :create]
 

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :city
  belongs_to :animalkind
  
  has_one :animal, dependent: :destroy
  has_one :announcementaddress, dependent: :destroy
  has_one :announcementcontact, dependent: :destroy
  
  #has_many :users, through: :favorites
  
  
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :city_id, presence: true
  validates :animalkind_id, presence: true
  validates :content, presence: true, length: { maximum: 1000 }
  validate  :picture_size
 
  private

  # Проводит валидацию размера загруженного изображения.
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :edit, :update]
  before_action :correct_user,   only: [:destroy, :edit, :update]
  before_action :check_my_info,   only: [:show]


  def create
   #debugger
    @announcement = current_user.announcements.build(announcement_params)
    #debugger
    if @announcement.save
      #animal = @announcement.build_animal
      #animal.save
      #debugger
      flash[:success] = "Основная информация про объявление сохранена"
      redirect_to new_animal_path
      #root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end
  
  def new
    @announcement = Announcement.new
    @categories = Category.all
    @cities = City.all
    @animalkinds = Animalkind.all
  end
  
  def index
    
    @categories = Category.all
    @cities = City.all
    @animalkinds = Animalkind.all
      
    if (params[:category_id].nil? && params[:city_id].nil? && params[:animalkind_id].nil?)
      @announcements = Announcement.paginate(page: params[:page])
    else
      announcementCategory = Announcement.where("cast(category_id as text) like ?", params[:category_id])
      #debugger
      announcementCategoryCity = announcementCategory.where("cast(city_id as text) like ?", params[:city_id])
      announcementCategoryCityAnimalkind = announcementCategoryCity.where("cast(animalkind_id as text) like ?", params[:animalkind_id])
      
      @announcements = announcementCategoryCityAnimalkind.paginate(page: params[:page])
   
      #debugger
    end
    
  end
  
  def edit
    @announcement = Announcement.find(params[:id])
    @categories = Category.all
    @cities = City.all
    @animalkinds = Animalkind.all
  end
  
  def update
    @announcement = Announcement.find(params[:id])
    if @announcement.update(announcement_params)
      # Обрабатывает успешное обновление
      flash[:success] = "Announcement updated"
      redirect_to @announcement
    else
      render 'edit'
    end
  end
  
   def show
     
    @announcement = Announcement.find(params[:id])
    @categories = Category.all
    @cities = City.all
    @animalkinds = Animalkind.all
   end
  
  def destroy
    @announcement.destroy
    flash[:success] = "Announcement deleted"
    redirect_to request.referrer || root_url
  end
  
  def check_my_info
    @announcement = Announcement.find(params[:id])
    
    if @announcement.animal.nil?
       animal = @announcement.build_animal
       animal.save
    end
    if @announcement.announcementaddress.nil?
       announcementaddress = @announcement.build_announcementaddress
       announcementaddress.save
    end
    if @announcement.announcementcontact.nil?
       announcementcontact = @announcement.build_announcementcontact
       announcementcontact.save
    end
    
    #debugger

  end

  private

   def announcement_params
     params.require(:announcement).permit(:content, :picture, :category_id, :city_id, :animalkind_id)
   end
   
    def first_announcement_params
      params.require(:announcement).permit(:category_id)
    end
    
    def correct_user
     
      if current_user.admin?
        user = Announcement.find(params[:id]).user
        @announcement = user.announcements.find_by(id: params[:id])
      else
        @announcement = current_user.announcements.find_by(id: params[:id])
      end
      redirect_to root_url if @announcement.nil?
    end
    
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_announcement.html.erb
<li id="announcement-<%= announcement.id %>">
  <%= link_to gravatar_for(announcement.user, size: 50), announcement.user %>
  <span class="user"><%= link_to announcement.user.name, announcement.user %></span>
 
<div class="blocks-wrapper">
<div class="minibloc1">
   <div class="blocks-wrapper">
 
    Категория:
    <div class ="littleblock">
    
    
     <%= @categories.find(announcement.category_id).typeCategory  %>
    </div>
     </div>
    
    <div class="blocks-wrapper">
        
    Город:
    <div class ="littleblock">
      <%= @cities.find(announcement.city_id).name %>
      </div>
      
    </div>
    
      <div class="blocks-wrapper">
    Вид животных:
    <div class ="littleblock">
      <%= @animalkinds.find(announcement.animalkind_id).kind %>
      </div>
    </div>
</div>
  
<%#     <% if announcement.animal.nil? %>
 <%#     Не указано
 <%#   <% else %>
 <%#       <%= announcement.animal.age %>
<%#    <% end %>
    
 <%#    <% if announcement.animal.nil? %>
 <%#     Не указано
<%#    <% else %>
 <%#       <%= announcement.animal.gender %>
 <%#   <% end %>
 <%#   
 <%#    <% if announcement.animal.nil? %>
  <%#    Не указано
  <%#  <% else %>
  <%#      <%= announcement.animal.breed %>
   <%# <% end %>
    
  <%#   <% if announcement.animal.nil? %>
   <%#   Не указано
  <%#  <% else %>
  <%#      <%= announcement.animal.color %>
  <%#  <% end %>
<div class="minibloc2">
    <div class = "littlebuttomspace">
        <%= link_to "Подробнее", announcement, id: "littlebuttom" %>
    </div>
    
     <% if !current_user.announcements.find_by(id: announcement.id) %>
     
        <% if !current_user.favorites.find_by(announcement_id: announcement.id) %>
            <div class = "littlebuttomspace">
                <%= link_to "В избранное", new_favorite_path(:announcement_id => announcement.id), id: "littlebuttom" %>
            </div>
           <% else %>
            <div class = "littlebuttomspace">
                <%= link_to "Удалить из избранного", favorite_path(Favorite.find_by(:announcement_id => announcement.id)), method: :delete, id: "redlittlebuttom" %>
            </div>
        <% end %>
    <% end %>
    <!--, class: "btn btn-lg btn-primary" -->
</div>
</div>
    <div class = "shortimg">
     <%= image_tag announcement.picture.url if announcement.picture? %>
    </div>
 
   
  <span class="timestamp">
    
    Posted <%= time_ago_in_words(announcement.created_at) %> ago.
    <% if current_user.admin? || current_user?(announcement.user) %>
      <%= link_to "delete", announcement, method: :delete, id: "redlittlebuttom",
                                       data: { confirm: "You sure?" } %>
      <%# <%= link_to "edit", edit_announcement_path(announcement) %>
                                       
                                       
    <% end %>
  </span>
</li>

app/views/announcements/edit.html.erb
<div class="MyBody">
<% provide(:title, "Edit announcement") %>
<h1>Изменение основной инорфмации объявления</h1>

<div class="MyContent">
  
  <%= render 'shared/edit_short_info' %>
  
  
<div class = "announcement1">
  <div class = "titleannouncement"> Информация про объявление: </div> 
    <div class = "info1">
      <%= form_for(@announcement) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        
          <%= f.text_area :content, class: 'form-control', cols: 30, rows: 7 %>
        
        <b>Ваша текущая картинка: </b>
         
        </br></br>
        
        <span class="content">
          <%= image_tag @announcement.picture.url if @announcement.picture? %>
        </span>
        
        </br></br>
        
        <b>Если хотите заменить выберите новую картинку:</b>
        
        </br></br>
        
        <span class="picture">
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
        </span>
     
        <div class = "btn-cont1">
          <%= f.submit "Сохранить", class: "btn btn-primary" %>
        </div>
        
      <% end %>
    </div> 
  </div> 
 
    
      
    <div class="blocks-wrapper">
    
      <%= render 'shared/edit_announcemetcontact' %>
      
      <%= render 'shared/edit_announcementaddress' %>
     
    </div>


    <%= render 'shared/edit_animal' %>
      
      </br></br>
</div>

</div>


<script type="text/javascript">
  $('#announcement_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/announcements/index.html.erb
<div class="MyBody" >
<% provide(:title, 'All users') %>
<h1>Все объявления</h1>

<%# <%= render 'users/search_form.html.erb' %>

<div class = "center">
    <%= will_paginate %>
</div> 
    
    <ul class="announcements">
        <%= render @announcements %>
    </ul>
    
<div class = "center">
    <%= will_paginate %>
</div> 

</div>

app/views/announcements/new.html.erb
<div class="MyBody">
    
<% provide(:title, "New announcement") %>
<h1>Создание объявления</h1>
  <h2>Основная информация</h2>

    <div class= "MyContent">
      <div class = "steptext">
        Шаг 1 из 4
      </div>
      <section class="announcement_form">
        <%= render 'shared/announcement_form' %>
      </section>
    
    </div>
</div>

app/views/announcements/show.html.erb
<div class="MyBody">
<% provide(:title, "Edit announcement") %>
<h1>Полная информация про объявление</h1>

<div class="MyContent">
      
  <%= render 'shared/edit_short_info' %>

  
    <%= render 'shared/edit_announcemet' %>
      
    <div class="blocks-wrapper">
    
    
    <%= render 'shared/edit_announcemetcontact' %>
    
    <%= render 'shared/edit_announcementaddress' %>
     
    </div>
    

    <%= render 'shared/edit_animal' %>
      
      </br></br>
      
</div>

</div>
<script type="text/javascript">
  $('#announcement_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>