config/routes.rb
Rails.application.routes.draw do
  
  get 'animalkinds/new'
  get 'favorites/new'
  get 'cities/new'
  get 'announcementcontacts/new'
  get 'announcementaddresses/new'
  get 'userinformations/new'
  get 'userinformation/new'
  get 'animals/new'
  get 'categories/new'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get 'search/announcements' => 'announcements#index'
  
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'search' => 'static_pages#search'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  post   'searchwithparams'   => 'static_pages#searchwithparams'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :announcements,   only: [:destroy, :index, :edit, :update, :new, :create, :show, :search]
  resources :categories,      only: [:index, :show]
  resources :animalkinds,      only: [:index, :show]
  resources :animals,         only: [:destroy, :edit, :new, :show, :index, :create, :update]
  resources :userinformations, only: [:destroy, :edit, :new, :show, :index, :create, :update]
  resources :announcementaddresses, only: [:destroy, :edit, :new, :show, :index, :create, :update]
  resources :announcementcontacts, only: [:destroy, :edit, :new, :show, :index, :create, :update]
  resources :favorites, only: [ :new, :index, :destroy, :create]
 

end

app/views/shared/_announcement_form.html.erb
<%= form_for(@announcement, html: { multipart: true }) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
 
  <div class="blocks-wrapper">
    <div class="text">
      <p> Информация про объявление: </p>
    </div>
    <div class="textAnn">
      <div class="field">
        <%= f.text_area :content, placeholder: "Опишите вашу ситуацию..." %>
      </div>
    </div>
  </div>
  
  <div class="blocks-wrapper">
  <div class="text">
    <p> Картинка: </p>
  </div>
    <span class="picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </span>
  </div>
  
  <div class="blocks-wrapper">
    <div class="text">
        <p> Категория: </p>
    </div>
    <div class="seldiv">
      <%= f.select :category_id, [['Розыск', 1],['Покупка', 2],['Продажа', 3],['Найден', 4]] %>
    </div>
    
  </div>
  
    <div class="blocks-wrapper">
    <div class="text">
        <p> Город: </p>
    </div>
    <div class="seldiv">
      <%= f.select :city_id, [['Москва', 1],['Санкт-Петербург', 2],['Нижний Новгород', 3],['Сочи', 4],['Казань', 5],['Ростов-на-Дону', 6]] %>
    </div>
    
  </div>
  
  <div class="blocks-wrapper">
    <div class="text">
        <p> Вид животного в объявлении: </p>
    </div>
    <div class="seldiv">
      <%= f.select :animalkind_id, [['Кошки', 1],['Собаки', 2],['Попугаи', 3]] %>
    </div>
    
  </div>

    <div class="post">
      <%= f.submit "Далее", class: "btn btn-primary" %>
    </div>
    
<% end %>

<script type="text/javascript">
  $('#announcement_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_edit_animal.html.erb
    <div class = "announcement2">
        
        <div class = "titleannouncement"> Информация про животное: </div> 
        <div class = "info4">
            
       
                
            <div class = "data1">
                   <b>Возраст: </b>
                  <%= @announcement.animal.age %>
                  <br>
                   <b>Пол: </b>
                  <%= @announcement.animal.gender %>
                  <br>
                   <b>Порода: </b>
                  <%= @announcement.animal.breed %>
                  <br>
                  <b>Цвет: </b>
                  <%= @announcement.animal.color %>
             </div>
       
             
              <% if current_user.admin? || current_user?(@announcement.user) %>
               <div class = "btn-cont1">
                   <%= link_to "Изменить", edit_animal_path(@announcement), class: "btn btn-lg btn-primary" %>
               </div>
              <% end %>
         </div>
    </div>

app/views/shared/_edit_announcementaddress.html.erb
    <div class = "announcement3">
        <div class = "titleannouncement"> Адресс: </div> 
        <div class = "info3">
            
  
                
            <div class = "data1">
                  <b>Улица: </b>
                  <%= @announcement.announcementaddress.street %>
                  <br>
                   <b>Дом: </b>
                  <%= @announcement.announcementaddress.house %>
                  <br>
                    <b>Квартира: </b>
                  <%= @announcement.announcementaddress.apartment %>
                  <br>
             </div>
             
     
             
              <% if current_user.admin? || current_user?(@announcement.user) %>
               <div class = "btn-cont1">
                   <%= link_to "Изменить", edit_announcementaddress_path(@announcement), class: "btn btn-lg btn-primary" %>
               </div>
              <% end %>
         </div>
    </div>

app/views/shared/_edit_announcemet.html.erb
   <div class = "announcement1">
      <div class = "titleannouncement"> Информация про объявление: </div> 
          <div class = "info1">

    
              <div class="field">
                 <textarea disabled>
                  <%= @announcement.content %>
                 </textarea>
              
            </div>
             
              </br></br>
               <%= image_tag @announcement.picture.url if @announcement.picture? %>
               
              <% if current_user.admin? || current_user?(@announcement.user) %>
               <div class = "btn-cont1">
                   <%= link_to "Изменить", edit_announcement_path(@announcement), class: "btn btn-lg btn-primary" %>
               </div>
               <% end %>
           </div>
    </div>
      
    

app/views/shared/_edit_announcemetcontact.html.erb
    <div class = "announcement4">
        <div class = "titleannouncement"> Контактная информация: </div> 
        <div class = "info2">
            
                
            <div class = "data1">
                  <b>Имя: </b>
                  <%= @announcement.announcementcontact.firstname %>
                  <br>
                   <b>Почта: </b>
                  <%= @announcement.announcementcontact.email %>
                  <br>
                   <b>Телефон: </b>
                  <%= @announcement.announcementcontact.phone %>
                <br>
             </div>

 
              <% if current_user.admin? || current_user?(@announcement.user) %>
               <div class = "btn-cont1">
                   <%= link_to "Изменить", edit_announcementcontact_path(@announcement), class: "btn btn-lg btn-primary" %>
               </div>
              <% end %>
         </div>
    </div>

app/views/shared/_edit_short_info.html.erb
<div class="minibloc1">
   <div class="blocks-wrapper">
 
    Категория:
    <div class ="littleblock">
    
    
     <%= @categories.find(@announcement.category_id).typeCategory  %>
    </div>
     </div>
    
    <div class="blocks-wrapper">
    Город:
    <div class ="littleblock">
    
    
      
      <%= @cities.find(@announcement.city_id).name %>
      </div>
    </div>
    
      <div class="blocks-wrapper">
    Вид животных:
    <div class ="littleblock">
    
    
      
      <%= @animalkinds.find(@announcement.animalkind_id).kind %>
      </div>
    </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>  <!--% if @user.errors.any? %>-->
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="announcements">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "Посмотреть профиль", current_user %></span>
<span><%= current_user.announcements.count %> объявлений </span>